//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Department { get; set; }
        public string DisplayName { get; set; }
        public string Manager { get; set; }
        public string ManagerEmail { get; set; }
        public string thumbnailPhoto { get; set; }
        public string Function { get; set; }
        public string Location { get; set; }
        public string DisplayName1 { get; set; }
        public string Country { get; set; }
        public string ErpNumber { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string FunctionSimpleDeal { get; set; }
        public string N_TRABAJADOR { get; set; }
        public string USUARIO_Sharepoint_Email { get; set; }
        public string USUARIO_Sharepoint_Nome { get; set; }
        public string AreaComercial { get; set; }
        public string Territory { get; set; }
    }
}
