//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Bank_Bnp
    {
        public int ID { get; set; }
        public string Type_Contract { get; set; }
        public string Type_Duration { get; set; }
        public Nullable<double> Contracto { get; set; }
        public Nullable<int> Volume_Start { get; set; }
        public Nullable<int> Volume_End { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> DespesaContracto { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> FinancingContractTypeID { get; set; }
    }
}
