//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_CRM_Quotes
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string quotenumber { get; set; }
        public string owneridname { get; set; }
        public string Guid { get; set; }
        public string statecodename { get; set; }
        public string statuscodename { get; set; }
        public Nullable<int> revisionnumber { get; set; }
        public string accountnumber { get; set; }
        public Nullable<double> new_kmtotalamount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
