//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Contactos
    {
        public int ID { get; set; }
        public string fullname { get; set; }
        public string emailaddress1 { get; set; }
        public string mobilephone { get; set; }
        public string telephone1 { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string ClientAccountNumberID { get; set; }
    }
}
