//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_CRM_Workflow
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string subject { get; set; }
        public string modifiedbyname { get; set; }
        public string owneridname { get; set; }
        public string regardingobjectidname { get; set; }
        public string statecode { get; set; }
        public string statecodename { get; set; }
        public string description { get; set; }
    }
}
