//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Commission_General
    {
        public int ID { get; set; }
        public string Agency { get; set; }
        public string Agency_Code { get; set; }
        public string Sales_Group { get; set; }
        public string Seller_Number { get; set; }
        public string Seller { get; set; }
        public string Manager_Number { get; set; }
        public string Manager { get; set; }
        public Nullable<int> CN_Year_Month { get; set; }
        public Nullable<int> Requested_Period { get; set; }
        public string HR_Comment { get; set; }
        public Nullable<bool> Invoice_List { get; set; }
        public string BB_Number { get; set; }
        public string BB_Full_Number { get; set; }
        public Nullable<int> SAP_Number { get; set; }
        public string Client_Number { get; set; }
        public string Client { get; set; }
        public string Billing { get; set; }
        public Nullable<double> Turnover { get; set; }
        public Nullable<double> Total_Margin { get; set; }
        public Nullable<double> Total_Margin_New { get; set; }
        public Nullable<double> Commission_On_Margin { get; set; }
        public Nullable<double> Maintenance_Commission { get; set; }
        public Nullable<double> Commissions { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<double> HW_CN { get; set; }
        public Nullable<double> HW_Margin { get; set; }
        public Nullable<double> HW_Margin_New { get; set; }
        public Nullable<double> HW_CN_Office { get; set; }
        public Nullable<double> HW_Margin_Office { get; set; }
        public Nullable<double> HW_CN_PP { get; set; }
        public Nullable<double> HW_Margin_PP { get; set; }
        public Nullable<double> HW_CN_IP { get; set; }
        public Nullable<double> HW_Margin_IP { get; set; }
        public Nullable<double> ITS_CN { get; set; }
        public Nullable<double> ITS_Margin { get; set; }
        public Nullable<double> PRS_CN { get; set; }
        public Nullable<double> PRS_Margin { get; set; }
        public Nullable<double> MCS_CN { get; set; }
        public Nullable<double> MCS_Margin { get; set; }
        public Nullable<double> BPS_CN { get; set; }
        public Nullable<double> BPS_Margin { get; set; }
        public Nullable<double> IMS_CN { get; set; }
        public Nullable<double> IMS_Margin { get; set; }
        public Nullable<double> WPH_CN { get; set; }
        public Nullable<double> WPH_Margin { get; set; }
        public Nullable<double> Mobotix_CN { get; set; }
        public Nullable<double> Mobotix_Margin { get; set; }
        public string Logs { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public Nullable<bool> Is_Controlled { get; set; }
        public Nullable<bool> Is_Commissioned { get; set; }
        public Nullable<bool> Is_Incident { get; set; }
        public Nullable<bool> Is_Excluded { get; set; }
        public Nullable<bool> Is_Second_Hand { get; set; }
        public Nullable<bool> Is_Doc_Share { get; set; }
        public Nullable<bool> Is_GMA { get; set; }
        public Nullable<bool> Is_Invoice_List { get; set; }
        public Nullable<bool> Support_BEU { get; set; }
        public Nullable<bool> CBB { get; set; }
        public string SAP_Client_Number { get; set; }
        public Nullable<bool> Is_Prospect { get; set; }
        public string Operation_Type { get; set; }
        public string Financing_Type { get; set; }
        public string Payment_Method { get; set; }
        public string Maintenance_Method { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
