//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Equipamentos
    {
        public int ID { get; set; }
        public string CodeRef { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> PVP { get; set; }
        public Nullable<double> PCT { get; set; }
        public Nullable<int> WorkSheet_MetadataID { get; set; }
        public Nullable<double> TCP { get; set; }
        public Nullable<double> ClickPriceBW { get; set; }
        public Nullable<double> ClickPriceC { get; set; }
        public string CRM_BW { get; set; }
        public string CRM_COLOR { get; set; }
        public Nullable<System.DateTime> EndOfService { get; set; }
        public Nullable<int> LifeExpectancy { get; set; }
        public Nullable<int> RecBWVolume { get; set; }
        public Nullable<int> RecCVolume { get; set; }
        public Nullable<double> BWBaseCost { get; set; }
        public Nullable<double> CBaseCost { get; set; }
        public string PHC1 { get; set; }
        public string PHC4 { get; set; }
        public string PHC5 { get; set; }
        public string PHC2 { get; set; }
        public string PHC3 { get; set; }
        public string PHC7 { get; set; }
        public Nullable<bool> InLineup { get; set; }
        public Nullable<int> AlfaModel { get; set; }
        public Nullable<int> Generation { get; set; }
    }
}
