//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_LocaisEnvio
    {
        public int ID { get; set; }
        public string Documento { get; set; }
        public string CodRef { get; set; }
        public string Description { get; set; }
        public string AccountNumber { get; set; }
        public string NomeCliente { get; set; }
        public string Quote { get; set; }
        public string ShipCode { get; set; }
        public string Adress1 { get; set; }
        public string Adress2 { get; set; }
        public string City { get; set; }
        public string Contacto { get; set; }
        public string PostalCode { get; set; }
        public string County { get; set; }
    }
}
