//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Logs_Proposal
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public string Collum { get; set; }
        public string Value { get; set; }
        public string Value_New { get; set; }
        public string ModifiedBy { get; set; }
    }
}
