//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Maquinas_Usadas_Pedidos
    {
        public int ID { get; set; }
        public string RequestTecnico { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string AccountManager { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comentarios { get; set; }
        public string PS_NUS { get; set; }
    }
}
