//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Maquinas_Usadas
    {
        public int ID { get; set; }
        public string NUS_DVCT { get; set; }
        public string NUS_DVCT_REGISTADA { get; set; }
        public Nullable<bool> Cat_Cancelado { get; set; }
        public string NUS_PS { get; set; }
        public string Nr_Entrada_Armazem { get; set; }
        public string NUS_Referencia { get; set; }
        public string ARM { get; set; }
        public string NUS_Modelo { get; set; }
        public string NUS_Tipo { get; set; }
        public string NUS_Nr_Serie { get; set; }
        public string Observacoes_Logistica { get; set; }
        public Nullable<System.DateTime> NUS_Data_Entrada_Equip { get; set; }
        public Nullable<int> Contador_Preto { get; set; }
        public Nullable<int> Contador_Cor { get; set; }
        public Nullable<int> Contador_Total { get; set; }
        public string Pedido_Por { get; set; }
        public Nullable<bool> Validar { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public string ReservedUser { get; set; }
        public Nullable<double> PriceUsed { get; set; }
    }
}
