//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_MIF_Renovations
    {
        public int ID { get; set; }
        public string ContractNr { get; set; }
        public string ContractType { get; set; }
        public string ParentContractNr { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime NewExpirationDate { get; set; }
        public string CustomerNr { get; set; }
        public string CustomerName { get; set; }
        public string InvoiceCustomerNr { get; set; }
        public string InvoiceCustomerName { get; set; }
        public string Segmentation { get; set; }
        public string TypeOfContract { get; set; }
        public string Delegation { get; set; }
        public string SalespersonCode { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonEmail { get; set; }
        public string ManagerEmail { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string PSNumber { get; set; }
        public string Antiquity { get; set; }
        public Nullable<bool> EndOfSales { get; set; }
        public Nullable<System.DateTime> SupplyBreakOffPlanDate { get; set; }
        public Nullable<System.DateTime> SupplyBreakOffDate { get; set; }
        public Nullable<int> TotalMif { get; set; }
        public string ProposalProgramCustomer { get; set; }
        public string Increase { get; set; }
        public string SalesServiceExceptions { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string Comments { get; set; }
        public string PriorityType { get; set; }
        public Nullable<int> State { get; set; }
    }
}
