//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Milestone
    {
        public int ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public string Family { get; set; }
        public string CodeRef { get; set; }
        public string Description { get; set; }
        public Nullable<double> UnitPriceCost { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> UnitDiscountPrice { get; set; }
        public Nullable<double> TotalNetSale { get; set; }
        public Nullable<int> Milestone { get; set; }
    }
}
