//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Maquinas_Usadas_Gestor
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public string ReservedBy { get; set; }
        public Nullable<System.DateTime> ReservedDateTime { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string PS_NUS { get; set; }
        public string Codref { get; set; }
        public string Type_MFP { get; set; }
        public string NrSerie { get; set; }
        public Nullable<int> NrCopyBW { get; set; }
        public Nullable<int> NrCopyCOLOR { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public string ClienteNr { get; set; }
        public string Comentarios { get; set; }
    }
}
