//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_PROPOSAL_CONDITIONS_MONITORIZATION
    {
        public int ID { get; set; }
        public int ProposalID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsStarted { get; set; }
        public bool IsProcessed { get; set; }
        public string Error { get; set; }
    }
}
