//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_Proposal()
        {
            this.BB_Proposal_OPSImplement = new HashSet<BB_Proposal_OPSImplement>();
            this.BB_Proposal_OPSManage = new HashSet<BB_Proposal_OPSManage>();
        }
    
        public int ID { get; set; }
        public string CRM_QUOTE_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<double> ValueTotal { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ClientAccountNumber { get; set; }
        public string AccountManager { get; set; }
        public Nullable<bool> ToDelete { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string StatusCRM1 { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> StatusCRM { get; set; }
        public Nullable<double> TaxaCopiaTotal { get; set; }
        public Nullable<double> SobreValorizacao { get; set; }
        public Nullable<double> ValueComission { get; set; }
        public Nullable<int> SapVersion { get; set; }
        public Nullable<bool> IsMultipleContract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Proposal_OPSImplement> BB_Proposal_OPSImplement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Proposal_OPSManage> BB_Proposal_OPSManage { get; set; }
    }
}
