//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Product_SubType
    {
        public int Id { get; set; }
        public string InternalCode { get; set; }
        public string ParentInternalCode { get; set; }
        public string Description { get; set; }
    }
}
