//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_PrintingService_Machines
    {
        public int PrintingServiceID { get; set; }
        public string CodeRef { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
        public Nullable<int> BWVolume { get; set; }
        public Nullable<int> CVolume { get; set; }
        public Nullable<double> BWPVP { get; set; }
        public Nullable<double> CPVP { get; set; }
        public Nullable<double> BWCost { get; set; }
        public Nullable<double> CCost { get; set; }
        public Nullable<double> ApprovedBW { get; set; }
        public Nullable<double> ApprovedC { get; set; }
        public Nullable<bool> IsInClient { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<double> RequestedBWClickPrice { get; set; }
        public Nullable<double> RequestedCClickPrice { get; set; }
    
        public virtual BB_PrintingServices BB_PrintingServices { get; set; }
    }
}
