//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_FinancingApproval
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<int> FinancingID { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsAproved { get; set; }
        public string Comments { get; set; }
    }
}
