//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_Condition_Type
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public string ConditionType { get; set; }
        public Nullable<double> ConditionValue { get; set; }
    }
}
