//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_Commission
    {
        public int ID { get; set; }
        public Nullable<double> PrintingHW_Commission { get; set; }
        public Nullable<double> ProductsITS_Commission { get; set; }
        public Nullable<double> ServicesITS_Commission { get; set; }
        public Nullable<double> IP_Commission { get; set; }
        public Nullable<double> WPH_Commission { get; set; }
        public Nullable<double> totalCommission { get; set; }
        public Nullable<int> ProposalID { get; set; }
    }
}
