//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_Financing
    {
        public int ID { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public string FinancingTypeCode1 { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> PaymentAfter { get; set; }
        public Nullable<bool> IncludeServices { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<int> FinancingTypeCode { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<double> MonthlyIncome { get; set; }
        public Nullable<System.DateTime> DateApproval { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<double> Factor { get; set; }
        public string AgreementNumber { get; set; }
        public Nullable<double> AmountNotFinanced { get; set; }
        public Nullable<double> AmountFinanced { get; set; }
        public Nullable<int> MaintanceContractDuration { get; set; }
        public Nullable<int> MaintanceContractPaymentMethodID { get; set; }
        public string MaintanceContractPaymentAfter { get; set; }
        public string MaintanceContractPaymentAfterText { get; set; }
        public string MaintanceContractPaymentTerms { get; set; }
    }
}
