//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_Vva
    {
        public int ID { get; set; }
        public Nullable<int> BWVolume { get; set; }
        public Nullable<int> CVolume { get; set; }
        public Nullable<double> MonthlyFee { get; set; }
        public Nullable<bool> UseGlobalValues { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<bool> UseGlobalExcess { get; set; }
        public Nullable<double> BWExcess { get; set; }
        public Nullable<double> CExcess { get; set; }
    }
}
