//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_DL_ClientContacts
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Tel { get; set; }
        public Nullable<int> Movil { get; set; }
        public string Email { get; set; }
    }
}
