//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_PrintingServices2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_Proposal_PrintingServices2()
        {
            this.BB_PrintingServices = new HashSet<BB_PrintingServices>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<int> ActivePrintingService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_PrintingServices> BB_PrintingServices { get; set; }
    }
}
