//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_PrintingServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_PrintingServices()
        {
            this.BB_Proposal_PrintingServiceValidationRequest = new HashSet<BB_Proposal_PrintingServiceValidationRequest>();
            this.BB_PrintingService_Machines = new HashSet<BB_PrintingService_Machines>();
        }
    
        public int PrintingServices2ID { get; set; }
        public Nullable<int> BWVolume { get; set; }
        public Nullable<int> CVolume { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public int ID { get; set; }
        public Nullable<bool> IsPrecalc { get; set; }
        public Nullable<double> Fee { get; set; }
    
        public virtual BB_Proposal_PrintingServices2 BB_Proposal_PrintingServices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Proposal_PrintingServiceValidationRequest> BB_Proposal_PrintingServiceValidationRequest { get; set; }
        public virtual BB_VVA BB_VVA { get; set; }
        public virtual BB_PrintingServices_NoVolume BB_PrintingServices_NoVolume { get; set; }
        public virtual BB_PrintingServices_ClickPerModel BB_PrintingServices_ClickPerModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_PrintingService_Machines> BB_PrintingService_Machines { get; set; }
    }
}
