//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_PrintingServices_NoVolume
    {
        public Nullable<double> GlobalClickBW { get; set; }
        public Nullable<double> GlobalClickC { get; set; }
        public Nullable<int> PageBillingFrequency { get; set; }
        public int PrintingServiceID { get; set; }
        public Nullable<double> RequestedGlobalClickBW { get; set; }
        public Nullable<double> RequestedGlobalClickC { get; set; }
    
        public virtual BB_PrintingServices BB_PrintingServices { get; set; }
    }
}
