//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_PsConfig
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<double> BWExcessCost { get; set; }
        public Nullable<double> CExcessCost { get; set; }
        public Nullable<double> BWDiscount { get; set; }
        public Nullable<double> CDiscount { get; set; }
        public Nullable<int> BWVolume { get; set; }
        public Nullable<double> BWCost { get; set; }
        public Nullable<int> CVolume { get; set; }
        public Nullable<double> CCost { get; set; }
        public Nullable<int> ItemID { get; set; }
    }
}
