//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_LeaseDesk_Detalhe
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<int> PropostaID { get; set; }
        public Nullable<int> Group { get; set; }
        public string Adress1 { get; set; }
        public string Adress2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Contacto { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CodeRef { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Description { get; set; }
    }
}
