//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_PROPOSAL_CONDITIONS_PERMACHINE
    {
        public int ID { get; set; }
        public string MachineModel { get; set; }
        public Nullable<int> Group { get; set; }
        public int ProposalID { get; set; }
        public string ConditionCode { get; set; }
        public double PVP { get; set; }
    }
}
