//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_PrintingServiceValidationRequest
    {
        public int PrintingServiceID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string SEObservations { get; set; }
        public string SCObservations { get; set; }
        public Nullable<System.DateTime> RequestedAt { get; set; }
        public string RequestedBy { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<bool> ToDelete { get; set; }
    
        public virtual BB_PrintingServices BB_PrintingServices { get; set; }
    }
}
