//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal_Quote_RS
    {
        public int ID { get; set; }
        public string CodeRef { get; set; }
        public string Description { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public string Family { get; set; }
        public Nullable<double> GPPercentage { get; set; }
        public Nullable<double> GPTotal { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<double> MonthlyFee { get; set; }
        public Nullable<double> MonthlyGP { get; set; }
        public Nullable<double> PVP { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> MonthlyFeeCost { get; set; }
        public Nullable<int> TotalMonths { get; set; }
        public Nullable<double> TotalNetsale { get; set; }
        public Nullable<double> TotalPVP { get; set; }
        public Nullable<double> UnitDiscountPrice { get; set; }
        public Nullable<double> UnitPriceCost { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<bool> IsFinanced { get; set; }
    }
}
