//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_REL_Equipament_Acessorie
    {
        public int ID { get; set; }
        public Nullable<int> ID_Equipament { get; set; }
        public Nullable<int> ID_Acessorie { get; set; }
    }
}
