//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_RD_MIF_Renovations_Program_Cost_Increments
    {
        public int Contract_Years { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public string Cost_Increase { get; set; }
    }
}
