//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_SLA_CategoriaCfg
    {
        public int ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Categoria { get; set; }
        public string State { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
