//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_SLA_DeptCatEstimateCfg
    {
        public int Id { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string StateDesc { get; set; }
        public Nullable<int> Estimate { get; set; }
    }
}
