//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_WFA_Control
    {
        public int ID { get; set; }
        public Nullable<int> BU_ID { get; set; }
        public Nullable<int> Elements_ID { get; set; }
        public Nullable<int> Level_ID { get; set; }
    }
}
