//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_WFA_Exception
    {
        public int ID { get; set; }
        public Nullable<int> WFA_ID { get; set; }
        public Nullable<int> WFA_Control_ID { get; set; }
        public Nullable<int> Line_ID { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Condition_ID { get; set; }
        public Nullable<double> Condition_Value { get; set; }
        public Nullable<int> Action_ID { get; set; }
        public Nullable<int> Level_ID { get; set; }
    }
}
