//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_WFA_Workflow_Proposal
    {
        public int ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Finished_Date { get; set; }
        public Nullable<bool> Started { get; set; }
        public Nullable<bool> Finished { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    }
}
