//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_DocumentProposal
    {
        public int ID { get; set; }
        public Nullable<int> ContratoID { get; set; }
        public string QuoteNumber { get; set; }
        public string Name { get; set; }
        public string Drive { get; set; }
        public string Folder { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string FileFullPath { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<bool> DocumentIsProcess { get; set; }
        public Nullable<bool> DocumentIsValid { get; set; }
        public string Comments { get; set; }
    }
}
