//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_DocSign_Control
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public Nullable<int> LeasedeskID { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> DocSignStatusSent { get; set; }
        public Nullable<System.DateTime> DocSignDateTimeSent { get; set; }
        public Nullable<int> NrPageSign { get; set; }
        public string DocPath { get; set; }
        public string DocSignEnvelopeID { get; set; }
        public string Message { get; set; }
    }
}
