//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_FinancingDocument
    {
        public int ID { get; set; }
        public Nullable<int> TipoFinanciamentoID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> IsOptional { get; set; }
    }
}
