//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_Logs
    {
        public int ID { get; set; }
        public Nullable<int> contratoID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public string TypeID { get; set; }
        public string Message { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Type { get; set; }
    }
}
