//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RD_AddressAcronyms
    {
        public int ID { get; set; }
        public Nullable<int> NrSAP { get; set; }
        public string SA { get; set; }
        public string Street { get; set; }
    }
}
