//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_get_DataIntegration
    {
        public int ID { get; set; }
        public string CodeRef { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> PVP { get; set; }
        public string BinaryImage { get; set; }
        public Nullable<bool> IsMarginBEU { get; set; }
        public Nullable<double> MarginBEU { get; set; }
        public string BOM { get; set; }
    }
}
