//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFA_FullDetails
    {
        public int WFA_Control_ID { get; set; }
        public Nullable<int> WFA_ID { get; set; }
        public Nullable<int> Line_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> BU_ID { get; set; }
        public Nullable<int> Elements_ID { get; set; }
        public int WFA_Level_ID { get; set; }
        public Nullable<int> Level { get; set; }
        public string WFA_Approver_ID { get; set; }
        public Nullable<int> Condition_ID { get; set; }
        public Nullable<double> Condition_Value { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public string BU_Description { get; set; }
        public string Element_Description { get; set; }
        public string Customer_Type { get; set; }
        public string Condition_Description { get; set; }
        public string Condition_Type_Description { get; set; }
        public Nullable<int> Condition2_ID { get; set; }
        public Nullable<double> Condition2_Value { get; set; }
        public Nullable<int> Type2_ID { get; set; }
        public string Condition2_Description { get; set; }
        public string Condition2_Type_Description { get; set; }
    }
}
